stop-words = "data/lemur-stopwords.txt"
prefix = "."
function-words = "data/function-words.txt"
punctuation = "data/sentence-boundaries/sentence-punctuation.txt"
start-exceptions = "data/sentence-boundaries/sentence-start-exceptions.txt"
end-exceptions = "data/sentence-boundaries/sentence-end-exceptions.txt"
query-judgements = "data/cranfield-qrels.txt"
query-path = "data/cranfield-queries.txt" # create this file

dataset = "apnews"
corpus = "line.toml" # located inside dataset folder
index = "index"
indexer-ram-budget = 1024 # **estimated** RAM budget for indexing in MB
                          # always set this lower than your physical RAM!

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500

[query-runner]
query-path = "/data/cranfield-queries.txt"
query-id-start = 1

