stop-words = "lemur-stopwords.txt"
prefix = "./data"
dataset = "cranfield"
corpus = "line.toml"
index = "cranfield-index"
query-judgements = "data/cranfield/cranfield-qrels.txt"

[query-runner]
query-path = "data/cranfield/cranfield-queries.txt"
query-id-start = 1

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
