stop-words = "data/lemur-stopwords.txt"
prefix = "."
dataset = "apnews"
corpus = "line.toml"
index = "apnews-index"
query-judgements = "qrels.txt"

[ranker]
method = "bm25"
k1 = 1.19999999999999996
b = 0.75000000000000000
k3 = 500.00000000000000000

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
