stop-words = "data/lemur-stopwords.txt"
prefix = "."
dataset = "wikipedia"
corpus = "line.toml"
index = "wikipedia-index2"

[ranker]
method = "dirichlet-prior"
mu = 2000.00000000000000000

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"
