prefix = ""

dataset = "cranfield"
corpus = "line.toml" # located inside dataset folder
index = "index"
indexer-ram-budget = 1024 # **estimated** RAM budget for indexing in MB
                          # always set this lower than your physical RAM!

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[ranker]
method = "bm25"
k1 = 1.2
b = 0.75
k3 = 500
